# Generated by Django 2.1.5 on 2019-02-09 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background_job', models.CharField(max_length=100)),
                ('background_location', models.CharField(max_length=100)),
                ('track', models.CharField(max_length=100)),
                ('track_progress', models.CharField(max_length=100)),
            ],
        ),
    ]
