# Generated by Django 2.1.5 on 2019-02-09 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractSpec',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skills', models.TextField()),
                ('employer', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='member',
            old_name='background_job',
            new_name='job',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='background_location',
            new_name='location',
        ),
        migrations.AddField(
            model_name='member',
            name='skills',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
