# Generated by Django 2.1.5 on 2019-02-10 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20190210_0349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='mentors',
            field=models.ManyToManyField(blank=True, null=True, related_name='_member_mentors_+', to='api.Member'),
        ),
    ]
