# Generated by Django 2.1.5 on 2019-02-10 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20190210_0512'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='mentor',
        ),
        migrations.AddField(
            model_name='member',
            name='mentor',
            field=models.ManyToManyField(related_name='_member_mentor_+', to='api.Member'),
        ),
    ]
