# Generated by Django 2.1.5 on 2019-02-10 05:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20190210_0513'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='mentor',
        ),
        migrations.AddField(
            model_name='member',
            name='mentor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Member'),
        ),
    ]
