# Generated by Django 2.1.5 on 2019-02-10 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20190210_0528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='mentor',
            field=models.TextField(default='null'),
        ),
        migrations.RemoveField(
            model_name='member',
            name='mentors',
        ),
        migrations.AddField(
            model_name='member',
            name='mentors',
            field=models.TextField(default='null'),
        ),
    ]
