# Generated by Django 2.1.5 on 2019-02-10 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20190210_0606'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='m_id',
        ),
    ]
