# Generated by Django 2.1.5 on 2019-02-10 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_member_m_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='m_id',
            field=models.TextField(default='null'),
        ),
    ]
