# Generated by Django 2.1.5 on 2019-02-10 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_member_m_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='mentors',
        ),
    ]
